/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/*
 * Copyright (c) 2012 University of Washington, 2012 INRIA
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

// Allow ns-3 to ping a real host somewhere, using emulation mode and ping
// the simulated node from the host.
//
//   +-------------------------------------+    
//   |                host                 |
//   +-------------------------------------+    
//   |    ns-3 simulation   |              |                       
//   +----------------------+              |    
//   |       ns-3 Node      |              |   
//   |  +----------------+  |              |   
//   |  |    ns-3 TCP    |  |              |   
//   |  +----------------+  |              |   
//   |  |    ns-3 IPv4   |  |              |   
//   |  +----------------+  |              |   
//   |  |   FdNetDevice  |  |              |  
//   |--+----------------+--+    +------+  |
//   |       | TAP  |            | eth0 |  | 
//   |       +------+            +------+  |
//   |       1.2.3.4                 |     |
//   +-------------------------------|-----+ 
//                                   |
//                                   |                             +-------------+
//                                   ------------ (Internet) ----- | Remote host |                            
//                                                                 +-------------+
//
// To use this example:
//  1) ns-3 will create the TAP device for you in the host machine.
//     For this you need to provide the network address to allocate IP addresses
//     for the TAP device and the ns-3 FdNetDevice.
//
//  2) Take into consideration that this experiment requires the host to be able
//     to forward traffic generated by the simulation to the Internet.
//     So for Linux systems, make sure to configure:
//     # echo 1 > /proc/sys/net/ipv4/ip_forward
//
//     Also enable natting so the ICMP replies from the remote host can reach 
//     back the TAP. 
//     - TAP-network-address is the same as 'tapNetwork'
//     - TAP-network-mask is the same as 'tapMask'
//     # iptables -t nat -A POSTROUTING -s <TAP-network-address>/<TAP-network-mask> -j MASQUERADE
//
//  3) Before running the example make sure that the tap creator binary has root suid.
//     If the --enable-sudo option was used to configure ns-3 with waf, then the following
//     step will not be necessary.
//
//     # chown root.root build/src/fd-net-device/ns3-dev-tap-device-creator
//     # sudo chmod 4755 build/src/fd-net-device/ns3-dev-tap-device-creator
//
//  4)  The example can be executed as follows using waf:
//  
//     ./waf --run fd-tap-ping --command-template="%s --tapNetwork=<TAP-network-address> --tapMask=<TAP-network-mask>" 
//

#include "ns3/abort.h"
#include "ns3/core-module.h"
#include "ns3/internet-module.h"
#include "ns3/network-module.h"
#include "ns3/fd-net-device-module.h"
#include "ns3/internet-apps-module.h"
#include "ns3/ipv4-static-routing-helper.h"
#include "ns3/ipv4-list-routing-helper.h"

using namespace ns3;

NS_LOG_COMPONENT_DEFINE ("TAPPingExample");

static void
PingRtt (std::string context, Time rtt)
{
  NS_LOG_UNCOND ("Received Response with RTT = " << rtt);
}

int
main (int argc, char *argv[])
{
  NS_LOG_INFO ("Ping Emulation Example with TAP");

  std::string deviceName ("tap0");
  std::string remote ("192.168.1.204"); // example.com
  std::string network ("10.1.1.0");
  std::string mask ("255.255.255.0");
  std::string pi ("no");

  //
  // Allow the user to override any of the defaults at run-time, via
  // command-line arguments
  //
  CommandLine cmd (__FILE__);
  cmd.AddValue ("deviceName", "Device name", deviceName);
  cmd.AddValue ("remote", "Remote IP address (dotted decimal only please)", remote);
  cmd.AddValue ("tapNetwork", "Network address to assign the TAP device IP address (dotted decimal only please)", network);
  cmd.AddValue ("tapMask", "Network mask for configure the TAP device (dotted decimal only please)", mask);
  cmd.AddValue ("modePi", "If 'yes' a PI header will be added to the traffic traversing the device(flag IFF_NOPI will be unset).", pi);
  cmd.Parse (argc, argv);

  NS_ABORT_MSG_IF (network == "1.2.3.4", "You must change the local IP address before running this example");

  Ipv4Address remoteIp (remote.c_str ());
  Ipv4Address tapNetwork (network.c_str ());
  Ipv4Mask tapMask (mask.c_str ());

  bool modePi = ( pi == "yes" ? true : false);

  //
  // Since we are using a real piece of hardware we need to use the realtime
  // simulator.
  //
  GlobalValue::Bind ("SimulatorImplementationType", StringValue ("ns3::RealtimeSimulatorImpl"));

  //
  // Since we are going to be talking to real-world machines, we need to enable
  // calculation of checksums in our protocols.
  //
  GlobalValue::Bind ("ChecksumEnabled", BooleanValue (true));

  //
  // In such a simple topology, the use of the helper API can be a hindrance
  // so we drop down into the low level API and do it manually.
  //
  // First we need a single node.
  //
  NS_LOG_INFO ("Create Node");
  Ptr<Node> node = CreateObject<Node> ();

  // Create an fd device, set a MAC address and point the device to the
  // Linux device name.  The device needs a transmit queueing discipline so
  // create a droptail queue and give it to the device.  Finally, "install"
  // the device into the node.
  //
  Ipv4AddressHelper addresses;
  addresses.SetBase (tapNetwork, tapMask);
  Ipv4Address tapIp = addresses.NewAddress ();

  NS_LOG_INFO ("Create Device");
  TapFdNetDeviceHelper helper;
  helper.SetDeviceName (deviceName);
  helper.SetModePi (modePi);
  helper.SetTapIpv4Address (tapIp);
  helper.SetTapIpv4Mask (tapMask);
  

  NetDeviceContainer devices = helper.Install (node);
  Ptr<NetDevice> device = devices.Get (0);
  //device->SetFileDescriptor(23); 

  //
  // Add a default internet stack to the node (ARP, IPv4, ICMP, UDP and TCP).
  //
  NS_LOG_INFO ("Add Internet Stack");
  InternetStackHelper internetStackHelper;
  internetStackHelper.Install (node);

  //
  // Add an address to the ns-3 device in the same network than one
  // assigned to the TAP.
  //
  NS_LOG_INFO ("Create IPv4 Interface");
  Ptr<Ipv4> ipv4 = node->GetObject<Ipv4> ();
  uint32_t interface = ipv4->AddInterface (device);
  Ipv4Address devIp = addresses.NewAddress ();
  Ipv4InterfaceAddress address = Ipv4InterfaceAddress (devIp, tapMask);
  ipv4->AddAddress (interface, address);
  ipv4->SetMetric (interface, 1);
  ipv4->SetUp (interface);

  //
  // Add a route to the ns-3 device so it can reach the outside world though the
  // TAP.
  //
  Ipv4StaticRoutingHelper ipv4RoutingHelper;
  Ptr<Ipv4StaticRouting> staticRouting = ipv4RoutingHelper.GetStaticRouting (ipv4);
  staticRouting->SetDefaultRoute (tapIp, interface);

  //
  // Create the ping application.  This application knows how to send
  // ICMP echo requests.  Setting up the packet sink manually is a bit
  // of a hassle and since there is no law that says we cannot mix the
  // helper API with the low level API, let's just use the helper.
  //
  NS_LOG_INFO ("Create V4Ping Appliation");
  Ptr<V4Ping> app = CreateObject<V4Ping> ();
  app->SetAttribute ("Remote", Ipv4AddressValue (remoteIp));
  app->SetAttribute ("Verbose", BooleanValue (true) );
  node->AddApplication (app);
  app->SetStartTime (Seconds (1.0));
  app->SetStopTime (Seconds (21.0));

  //
  // Give the application a name.  This makes life much easier when constructing
  // config paths.
  //
  Names::Add ("app", app);

  //
  // Hook a trace to print something when the response comes back.
  //
  Config::Connect ("/Names/app/Rtt", MakeCallback (&PingRtt));

  //
  // Enable a promiscuous pcap trace to see what is coming and going on our device.
  //
  helper.EnablePcap ("fd-tap-ping", device, true);

  //
  // Now, do the actual emulation.
  //
  NS_LOG_INFO ("Run Emulation.");
  Simulator::Stop (Seconds (45.0));
  Simulator::Run ();
  Simulator::Destroy ();
  NS_LOG_INFO ("Done.");
}

//
// #include <iostream>
// #include <fstream>

// #include "ns3/core-module.h"
// #include "ns3/network-module.h"
// #include "ns3/csma-module.h"
// #include "ns3/tap-bridge-module.h"
// #include "ns3/internet-module.h"
// #include "ns3/flow-monitor-helper.h"
// #include "ns3/flow-monitor-module.h"
// #include "ns3/netanim-module.h"
// #include "ns3/config-store-module.h"
// #include "ns3/wifi-module.h"
// #include "ns3/mobility-module.h"

// using namespace ns3;

// NS_LOG_COMPONENT_DEFINE ("MPTapCsmaVirtualMachineExample");

// void ThroughputMonitor (FlowMonitorHelper* fmhelper, Ptr<FlowMonitor> flowMon)
// {
//   flowMon->CheckForLostPackets();
//   std::map<FlowId, FlowMonitor::FlowStats> flowStats = flowMon->GetFlowStats();
//   Ptr<Ipv4FlowClassifier> classing = DynamicCast<Ipv4FlowClassifier> (fmhelper->GetClassifier());
//   for (std::map<FlowId, FlowMonitor::FlowStats>::const_iterator stats = flowStats.begin (); stats != flowStats.end (); ++stats)
//   {
//     Ipv4FlowClassifier::FiveTuple fiveTuple = classing->FindFlow (stats->first);
//     std::cout<<"Flow ID                 : " << stats->first <<" ; "<< fiveTuple.sourceAddress <<" -----> "<<fiveTuple.destinationAddress<<std::endl;
// //  std::cout<<"Tx Packets = " << stats->second.txPackets<<std::endl;
// //  std::cout<<"Rx Packets = " << stats->second.rxPackets<<std::endl;
//     std::cout<<"Duration                : "<<stats->second.timeLastRxPacket.GetSeconds()-stats->second.timeFirstTxPacket.GetSeconds()<<std::endl;
//     std::cout<<"Last Received Packet    : "<< stats->second.timeLastRxPacket.GetSeconds()<<" Seconds"<<std::endl;
//     std::cout<<"Throughput: " << stats->second.rxBytes * 8.0 / (stats->second.timeLastRxPacket.GetSeconds()-stats->second.timeFirstTxPacket.GetSeconds())/1024/1024  << " Mbps"<<std::endl;
//     std::cout<<"---------------------------------------------------------------------------"<<std::endl;
//   }

//  // Rescheduling the next call to this function to print throughput
//  Simulator::Schedule(Seconds(3),&ThroughputMonitor, fmhelper, flowMon);

// }

// // Parse context strings of the form "/NodeList/x/DeviceList/x/..." to extract the NodeId integer
// uint32_t
// ContextToNodeId (std::string context)
// {
//   std::string sub = context.substr (10);
//   uint32_t pos = sub.find ("/Device");
//   return atoi (sub.substr (0, pos).c_str ());
// }

// void
// PhyRxErrorTrace (std::string context, Ptr<const Packet> p, double snr)
// {
//   std::cout << "PHY-RX-ERROR time=" << Simulator::Now () << " node=" << ContextToNodeId (context)
//             << " size=" << p->GetSize () << " snr=" << snr << std::endl;
// }

// void
// PhyRxDropTrace (std::string context, Ptr<const Packet> p, WifiPhyRxfailureReason reason)
// {
//   std::cout << "PHY-RX-DROP time=" << Simulator::Now () << " node=" << ContextToNodeId (context)
//             << " size=" << p->GetSize () << " reason=" << reason << std::endl;
// }

// int 
// main (int argc, char *argv[])
// {
//   std::cout << "Start simulation "<< std::endl;
//   CommandLine cmd (__FILE__);
//   cmd.Parse (argc, argv);

//   //Config::SetDefault ("ns3::DropTailQueue<Packet>::MaxSize", StringValue ("100p"));
  
  
//   // We are interacting with the outside, real, world.  This means we have to 
//   // interact in real-time and therefore means we have to use the real-time
//   // simulator and take the time to calculate checksums.
//   //
//   GlobalValue::Bind ("SimulatorImplementationType", StringValue ("ns3::RealtimeSimulatorImpl"));
//   GlobalValue::Bind ("ChecksumEnabled", BooleanValue (true));

//   //
//   // Create two ghost nodes.  The first will represent the virtual machine host
//   // on the left side of the network; and the second will represent the VM on 
//   // the right side.
//   //
//   NodeContainer nodes;
//   nodes.Create (2);

//   NodeContainer middle;
//   middle.Create(1);     // create one node in the middle 

//   NodeContainer left_m (nodes.Get(0), middle.Get(0));
//   NodeContainer right_m (nodes.Get(1), middle.Get(0));

//   // ./waf --run "tap=csma-virtual-machine --ns3::CsmaChannel::DataRate=10000000"
//   //
  
//   // // create default  wifi  channel 
//   // YansWifiChannelHelper wifiChannel = YansWifiChannelHelper::Default ();
//   // YansWifiPhyHelper wifiPhy;
//   // wifiPhy.SetChannel (wifiChannel.Create ());
//   // // Add a mac and Set it to adhoc mode
//   // WifiMacHelper wifiMac;
//   // wifiMac.SetType ("ns3::AdhocWifiMac");
//   // // wifi helper 
//   // WifiHelper wifi;
//   // wifi.SetStandard (WIFI_STANDARD_80211n_2_4GHZ);
//   // Config::SetDefault ("ns3::LogDistancePropagationLossModel::ReferenceLoss", DoubleValue (40.046));
//   // wifi.SetRemoteStationManager ("ns3::ConstantRateWifiManager",
//   //                                       "DataMode", StringValue("HtMcs7"),
//   //                                       "ControlMode", StringValue("HtMcs7"));
  

//   // std::string phyMode ("DsssRate1Mbps");
  
//   // // disable fragmentation for frames below 2200 bytes
//   // Config::SetDefault ("ns3::WifiRemoteStationManager::FragmentationThreshold",
//   //                     StringValue ("2200"));
//   // // turn off RTS/CTS for frames below 2200 bytes
//   // Config::SetDefault ("ns3::WifiRemoteStationManager::RtsCtsThreshold",
//   //                     StringValue ("2200"));
//   // // Fix non-unicast data rate to be the same as that of unicast
//   // Config::SetDefault ("ns3::WifiRemoteStationManager::NonUnicastMode",
//   //                     StringValue (phyMode));

//   // Config::SetDefault ("ns3::WifiRemoteStationManager::RtsCtsThreshold", StringValue ("999999"));
//   // YansWifiPhyHelper wifiPhy;

//   // /** wifi channel **/
//   // YansWifiChannelHelper wifiChannel;
//   // wifiChannel.SetPropagationDelay ("ns3::ConstantSpeedPropagationDelayModel");
//   // //wifiChannel.AddPropagationLoss ("ns3::FriisPropagationLossModel");
//   // double rss = -80; 
//   // wifiChannel.AddPropagationLoss ("ns3::FixedRssLossModel","Rss",DoubleValue (rss));

//   // // create wifi channel
//   // Ptr<YansWifiChannel> wifiChannelPtr = wifiChannel.Create ();
//   // wifiPhy.SetChannel (wifiChannelPtr);

//   /** Wifi PHY **/
//   /***************************************************************************/
//   // create default  wifi  channel 
//   YansWifiChannelHelper wifiChannel = YansWifiChannelHelper::Default ();
//   YansWifiPhyHelper wifiPhy;
//   wifiPhy.SetPcapDataLinkType (WifiPhyHelper::DLT_IEEE802_11_RADIO);  
//   wifiPhy.SetChannel (wifiChannel.Create ());

//   /** MAC layer **/
//    // Add a mac and Set it to adhoc mode
//   WifiMacHelper wifiMac;
//   wifiMac.SetType ("ns3::AdhocWifiMac");
  
//   // wifi helper 
//   WifiHelper wifi;
//   wifi.SetStandard (WIFI_STANDARD_80211a);
//   wifi.SetRemoteStationManager ("ns3::ConstantRateWifiManager", "DataMode",
//                                 StringValue ("OfdmRate54Mbps"), 
//                                 "ControlMode", StringValue ("OfdmRate24Mbps"));

  
//   // set possition and mobility model 
//   Ptr<ListPositionAllocator> positionAllocWifi = CreateObject<ListPositionAllocator> ();
//   positionAllocWifi->Add (Vector (0.0, 0.0, 0.0));
//   positionAllocWifi->Add (Vector (5, 0, 0));
//   positionAllocWifi->Add (Vector (15, 0, 0));
//   MobilityHelper mobility;
//   mobility.SetPositionAllocator (positionAllocWifi);
//   mobility.SetMobilityModel ("ns3::ConstantPositionMobilityModel");
//   mobility.Install (left_m.Get (0));
//   mobility.Install (left_m.Get (1));
//   mobility.Install (nodes.Get(1)); 

//   // dev conteiner of wifi devices starting from left
//   NetDeviceContainer leftDev = wifi.Install (wifiPhy, wifiMac, left_m);

//   CsmaHelper csma;
//   csma.SetChannelAttribute ("DataRate", StringValue ("100Mbps"));
//   csma.SetChannelAttribute ("Delay", TimeValue (MicroSeconds (5)));
//   NetDeviceContainer rightDev = csma.Install (right_m);
  
//   //internet for middle 
//   InternetStackHelper inet; 
//   inet.Install (middle);

//   // Assign adress to AP wifi inface
//   Ipv4AddressHelper ipv4h; 
//   ipv4h.SetBase ("15.0.0.0", "255.0.0.0", "0.0.0.1");
//   Ipv4InterfaceContainer middle1iface = ipv4h.Assign (leftDev.Get(1));
//   ipv4h.SetBase ("14.0.0.0", "255.0.0.0", "0.0.0.1");
//   Ipv4InterfaceContainer middle2iface = ipv4h.Assign (rightDev.Get(1));

//   //
//   // Use the TapBridgeHelper to connect to the pre-configured tap devices for
//   // the left side.  We go with "UseBridge" mode since the CSMA devices support
//   // promiscuous mode and can therefore make it appear that the bridge is
//   // extended into ns-3.  The install method essentially bridges the specified
//   // tap to the specified CSMA device.
//   //
//   TapBridgeHelper tapBridge;
//   tapBridge.SetAttribute ("Mode", StringValue ("UseLocal"));

//   // tapBridge.SetAttribute ("DeviceName", StringValue ("tap-left"));
//   // tapBridge.Install (nodes.Get (0), leftDev.Get (0));
//   tapBridge.SetAttribute ("DeviceName", StringValue ("tap-left-1"));
//   tapBridge.Install (nodes.Get (0), leftDev.Get (0));

//   //
//   // Connect the right side tap to the right side CSMA device on the right-side
//   // ghost node.
//   //
//   // tapBridge.SetAttribute ("DeviceName", StringValue ("tap-right"));
//   // tapBridge.Install (nodes.Get (1), devices.Get (1));

//   tapBridge.SetAttribute ("DeviceName", StringValue ("tap-right-1"));
//   tapBridge.Install (nodes.Get (1), rightDev.Get (0));

//   // Trace PHY Rx error events
//   Config::Connect ("/NodeList/*/DeviceList/*/$ns3::WifiNetDevice/Phy/$ns3::WifiPhy/State/RxError",
//                    MakeCallback (&PhyRxErrorTrace));
//   // Trace PHY Rx drop events
//   Config::Connect ("/NodeList/*/DeviceList/*/$ns3::WifiNetDevice/Phy/$ns3::WifiPhy/PhyRxDrop",
//                    MakeCallback (&PhyRxDropTrace));

//   csma.EnablePcapAll ("mp-csma-3", true);
//   // wifi ENABLE PCAP
//   wifiPhy.EnablePcapAll ("mp-wifi-lte", true);

//   Config::SetDefault ("ns3::ConfigStore::Filename", StringValue ("output-attributes.txt"));
//   Config::SetDefault ("ns3::ConfigStore::FileFormat", StringValue ("RawText"));
//   Config::SetDefault ("ns3::ConfigStore::Mode", StringValue ("Save"));
//   ConfigStore outputConfig2;
//   outputConfig2.ConfigureDefaults ();
//   outputConfig2.ConfigureAttributes ();

//   std::cout << "Stop simulation \n";
//   Simulator::Stop (Seconds (600.0));
//   Simulator::Run ();
//   Simulator::Destroy ();
  
//   //flowMonitor->SerializeToXmlFile("mp-monitor.xml", true, true);
// }
